version: '3.8'

services:

  postgresdb:
    image: postgres:17
    container_name: postgresDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shoppingDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi-backend:
    container_name: fastapi-backend
    environment:
      DATABASE_URL: postgresql://admin:admin@postgresDB/shoppingDB
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgresdb
        


volumes:
  postgres_data:
