version: '3.9'

services:

  postgresdb:
    image: postgres
    container_name: postgresDb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shoppingDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi-backend:
    container_name: fastapi-backend
    environment:
      DATABASE_URL: postgresql://admin:admin@postgresDb/shoppingDb
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
        


volumes:
  postgres_data:
